-- Supabase migration blueprint for the Saima portfolio
create table if not exists public.portfolio_profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  headline text not null,
  bio text not null,
  availability text not null,
  portrait_url text,
  github_url text,
  linkedin_url text,
  twitter_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.portfolio_technologies (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.portfolio_projects (
  id bigint generated by default as identity primary key,
  title text not null,
  project_type text not null,
  summary text not null,
  image_url text not null,
  project_url text,
  tags text[] not null default '{}',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 120),
  email text not null check (char_length(email) between 3 and 320),
  message text not null check (char_length(message) between 10 and 5000),
  created_at timestamptz not null default now()
);

alter table public.portfolio_profiles enable row level security;
alter table public.portfolio_technologies enable row level security;
alter table public.portfolio_projects enable row level security;
alter table public.contact_submissions enable row level security;

create policy "public can read portfolio profiles" on public.portfolio_profiles for select using (true);
create policy "public can read portfolio technologies" on public.portfolio_technologies for select using (true);
create policy "public can read portfolio projects" on public.portfolio_projects for select using (true);
create policy "public can submit contact requests" on public.contact_submissions for insert with check (true);
